[package]
name = "render_stl"
version = "0.4.0"
edition = "2021"

[dependencies]
cgmath = "0.18"
futures = "0.3"
image = "0.24.7"
mesh = { path = "../mesh" }
ray_tracer = { path = "../ray_tracer" }
thiserror = "1.0.48"
typed-arena = "2"
