[package]
name = "part_renderer_cli"
version = "0.1.0"
edition = "2018"

[dependencies]
cgmath = "0.18"
clap = "2.33.3"
futures = "0.3"
image = "0.23"
mesh = { path = "../mesh" }
renderer = { path = "../renderer" }
ron = "0.6.4"
serde = { version = "1.0", features = ["derive"] }
typed-arena =  "2"
